import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { VideoView, useVideoPlayer } from 'expo-video';
// Generated by: node scripts/Generatessignmanifest.js
import { SIGN_VIDEOS } from '../../speech_to_sign_videos/signVideos';
import { useSpeechToText } from '../hooks/Usespeechtotext';
import GlowButton from '../components/GlowButton'; // adjust path
import { COLORS } from '../constants/theme'; // adjust path

type Item =
  | { id: number; kind: 'video'; label: string; source: number }
  | { id: number; kind: 'word'; label: string };

// Spoken variants -> manifest label. Extend as needed.
const ALIASES: Record<string, string> = { okay: 'ok' };
const SPEEDS = [0.5, 0.75, 1, 1.25, 1.5, 2];
const START_OFFSET = 0.5; // seconds to skip; the sign starts a moment after the clip does
const END_TRIM = 0.5;     // seconds skipped at the end
// Keeping up with speech (tune these):
const MAX_BACKLOG = 4;       // items allowed to wait; older ones are dropped to stay current
const CATCH_UP_RATE = 1.75;  // extra speed multiplier while 2+ items are waiting
const WORD_MS = 700;         // how long an unsupported word shows at 1x
const STALL_MS = 15000;      // give up on a clip that never finishes loading/playing

let nextId = 1;

const lookup = (label: string): number | undefined =>
  Object.prototype.hasOwnProperty.call(SIGN_VIDEOS, label) ? SIGN_VIDEOS[label] : undefined;

/** Turn recognized words into videos (known words) and words (unknown). */
function toItems(text: string): Item[] {
  const tokens = text
    .toLowerCase()
    .split(/\s+/)
    .map((t) => t.replace(/[^a-z]/g, ''))
    .filter(Boolean);

  const items: Item[] = [];
  let i = 0;
  while (i < tokens.length) {
    let matched = false;

    // Longest phrase first: "hard of hearing" -> hardofhearing, "call tty" -> calltty
    for (let n = Math.min(3, tokens.length - i); n >= 1; n--) {
      const key = tokens.slice(i, i + n).join('');
      if (key.length === 1) continue; // single letters are for fingerspelling, not words
      const label = ALIASES[key] ?? key;
      const source = lookup(label);
      if (source !== undefined) {
        items.push({ id: nextId++, kind: 'video', label, source });
        i += n;
        matched = true;
        break;
      }
    }

    if (!matched) {
      items.push({ id: nextId++, kind: 'word', label: tokens[i] });
      i++;
    }
  }
  return items;
}

export default function SpeechSign() {
  const insets = useSafeAreaInsets();
  const [current, setCurrent] = useState<Item | null>(null);
  const [speed, setSpeed] = useState(1);
  const [menuOpen, setMenuOpen] = useState(false);

  const queueRef = useRef<Item[]>([]);
  const currentRef = useRef<Item | null>(null);
  const speedRef = useRef(1);
  speedRef.current = speed;

  // Chosen speed, boosted while the queue is backing up
  const effectiveRate = () => speedRef.current * (queueRef.current.length >= 2 ? CATCH_UP_RATE : 1);

  const advance = useCallback(() => {
    const next = queueRef.current.shift() ?? null;
    currentRef.current = next;
    setCurrent(next);
  }, []);

  // Words arrive as they are recognized; if nothing is playing, start right away.
  const handleWords = useCallback(
    (text: string) => {
      queueRef.current.push(...toItems(text));
      while (queueRef.current.length > MAX_BACKLOG) queueRef.current.shift();
      if (!currentRef.current) advance();
    },
    [advance]
  );

  const { listening, error } = useSpeechToText(handleWords);

  const player = useVideoPlayer(null, (p) => {
    p.loop = false;
    p.muted = true;
  });

  // Play the current video
  // Play the current video, starting at START_OFFSET
  const readyRef = useRef(false);

// Play the current video, starting at START_OFFSET
  useEffect(() => {
    if (current?.kind !== 'video') return;

    readyRef.current = false;
    player.replace(current.source);
    player.currentTime = START_OFFSET;
    player.playbackRate = effectiveRate();
    player.play();

    const sub = player.addListener('statusChange', ({ status }) => {
      if (status === 'readyToPlay') {
        player.currentTime = START_OFFSET;
        readyRef.current = true;
        sub.remove();
      }
    });
    return () => sub.remove();
  }, [player, current]);

  // Speed changed mid-video
  useEffect(() => {
    player.playbackRate = effectiveRate();
  }, [player, speed]);

  // Next item when a video finishes (or fails to load)
  useEffect(() => {
    const endSub = player.addListener('playToEnd', advance);
    const statusSub = player.addListener('statusChange', ({ status }) => {
      if (status === 'error') advance();
    });
    return () => {
      endSub.remove();
      statusSub.remove();
    };
  }, [player, advance]);

  // Stop END_TRIM seconds before the clip ends
  useEffect(() => {
    player.timeUpdateEventInterval = 0.05;
    const sub = player.addListener('timeUpdate', ({ currentTime }) => {
      if (!readyRef.current || currentRef.current?.kind !== 'video') return;
      const d = player.duration;
      if (d > START_OFFSET + END_TRIM && currentTime >= d - END_TRIM) {
        readyRef.current = false; // make sure it only advances once
        advance();
      }
    });
    return () => sub.remove();
  }, [player, advance]);

  // Watchdog: a clip that never finishes must not freeze the whole queue
  useEffect(() => {
    if (current?.kind !== 'video') return;
    const t = setTimeout(advance, STALL_MS);
    return () => clearTimeout(t);
  }, [current, advance]);

  // Unsupported words show briefly, scaled by speed
  useEffect(() => {
    if (current?.kind !== 'word') return;
    const t = setTimeout(advance, Math.max(350, WORD_MS / effectiveRate()));
    return () => clearTimeout(t);
  }, [current, speed, advance]);

  return (
    <View
      style={[
        styles.screen,
        { paddingTop: insets.top + 16, paddingBottom: insets.bottom + 16 },
      ]}
    >
      <View style={styles.box}>
        <View
          style={[StyleSheet.absoluteFill, current?.kind !== 'video' && styles.hidden]}
          pointerEvents="none"
        >
          <VideoView
            player={player}
            style={styles.video}
            contentFit="contain"
            nativeControls={false}
          />
        </View>
        {current?.kind === 'word' && (
          <View style={styles.center} pointerEvents="none">
            <Text style={styles.word}>{current.label}</Text>
          </View>
        )}

        {!current && !error && (
          <View style={styles.center} pointerEvents="none">
            <Text style={styles.idle}>{listening ? 'Waiting for speech' : 'Starting microphone'}</Text>
          </View>
        )}

        {error && (
          <View style={styles.center} pointerEvents="none">
            <Text style={styles.error}>{error}</Text>
          </View>
        )}

        {!error && (
          <View style={styles.status}>
            <View style={[styles.dot, listening && styles.dotOn]} />
            <Text style={styles.statusText}>{listening ? 'Listening' : 'Starting microphone'}</Text>
          </View>
        )}

        {menuOpen && <Pressable style={styles.backdrop} onPress={() => setMenuOpen(false)} />}

        <View style={styles.speedWrap}>
          {menuOpen && (
            <View style={styles.menu}>
              {SPEEDS.map((s) => (
                <Pressable
                  key={s}
                  accessibilityRole="button"
                  accessibilityLabel={`Playback speed ${s}x`}
                  onPress={() => {
                    setSpeed(s);
                    setMenuOpen(false);
                  }}
                  style={[styles.option, s === speed && styles.optionActive]}
                >
                  <Text style={styles.optionText}>{s}x</Text>
                </Pressable>
              ))}
            </View>
          )}
          <GlowButton
            radius={12}
            accessibilityRole="button"
            accessibilityLabel="Change playback speed"
            onPress={() => setMenuOpen((o) => !o)}
            style={styles.speedBtn}
            contentStyle={styles.speedInner}
          >
            <Text style={styles.speedText}>{speed}x ▾</Text>
          </GlowButton>
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  video: { width: '100%', height: '100%' },
  screen: { flex: 1, backgroundColor: COLORS.bg, paddingHorizontal: 16 },
  box: {
    flex: 1,
    width: '100%',
    maxWidth: 960,
    alignSelf: 'center',
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: '#000',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  hidden: { opacity: 0 },
  center: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  word: { color: '#fff', fontSize: 56, fontWeight: '700', textAlign: 'center' },
  idle: { color: COLORS.muted, fontSize: 18, textAlign: 'center' },
  error: { color: COLORS.danger, fontSize: 16, textAlign: 'center' },

  status: {
    position: 'absolute',
    top: 12,
    left: 12,
    zIndex: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(0,0,0,0.55)',
  },
  dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#777' },
  dotOn: { backgroundColor: '#4ade80' },
  statusText: { color: '#ddd', fontSize: 13 },

  backdrop: { ...StyleSheet.absoluteFillObject, zIndex: 5 },
  speedWrap: { position: 'absolute', right: 12, bottom: 12, zIndex: 10, alignItems: 'flex-end' },
  speedBtn: {
    borderRadius: 12,
    backgroundColor: 'rgba(10,42,107,0.92)',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  speedInner: { paddingHorizontal: 14, paddingVertical: 8 },
  speedText: { color: '#fff', fontSize: 15, fontWeight: '600' },
  menu: {
    marginBottom: 8,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: 'rgba(10,42,107,0.97)',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  option: { paddingHorizontal: 18, paddingVertical: 10 },
  optionActive: { backgroundColor: 'rgba(255,255,255,0.16)' },
  optionText: { color: '#fff', fontSize: 15 },
});