// Run from the project root:  node scripts/generateSignManifest.js
// Scans speech_to_sign_videos/*.mp4 and writes speech_to_sign_videos/signVideos.ts
// (React Native / Metro can only bundle videos referenced with a static require(),
//  so we can't build the file path from the spoken word at runtime.)

const fs = require('fs');
const path = require('path');

const DIR = path.join(__dirname, '..', 'speech_to_sign_videos');
const OUT = path.join(DIR, 'signVideos.ts');

const normalize = (s) => s.toLowerCase().replace(/[^a-z]/g, '');

// "0783156344745779-SMOKE.mp4" -> "smoke",  "...-NOT INTERESTED.mp4" -> "notinterested"
const labelOf = (file) =>
  normalize(file.replace(/\.mp4$/i, '').replace(/^[\d_\-]+/, ''));

const files = fs.readdirSync(DIR).filter((f) => /\.mp4$/i.test(f)).sort();

const byLabel = {};
for (const f of files) {
  const label = labelOf(f);
  if (label && !byLabel[label]) byLabel[label] = f; // first video per label
}

const labels = Object.keys(byLabel).sort();
const lines = labels.map(
  (l) => `  ${JSON.stringify(l)}: require(${JSON.stringify('./' + byLabel[l])}),`
);

const out = `// AUTO-GENERATED by scripts/generateSignManifest.js - do not edit by hand.
export const SIGN_VIDEOS: Record<string, number> = {
${lines.join('\n')}
};
`;

fs.writeFileSync(OUT, out);
console.log(`Wrote ${labels.length} entries to ${path.relative(process.cwd(), OUT)}`);
console.log('Labels:', labels.join(', '));